os:
  - linux
jdk:
  - oraclejdk8
language: java
sudo: false
script: mvn clean verify
#notifications:
 # slack:
  #  rooms:
   #   - epam-krk-ja-2016:lCrvreRSWu6W2ulh5zEqvRQd#dream-team
#TODO to add later the notification